# coding: utf-8
from enum import IntEnum


MESSAGE_USER_LOGIN = 'USER_LOGIN'
MESSAGE_USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
MESSAGE_USER_UPDATE_STATE = 'USER_UPDATE_STATE'

MESSAGE_GAME_CREATE = 'GAME_CREATE'
MESSAGE_GAME_JOIN = 'GAME_JOIN'
MESSAGE_GAME_MOVE = 'GAME_MOVE'
MESSAGE_GAME_LEAVE = 'GAME_LEAVE'
MESSAGE_GAME_ERROR = 'GAME_ERROR'


class GameState(IntEnum):
    EMPTY = 0
    WAITING = 1
    IN_PROGRESS = 2
    FINISHED = 3
